### PR TITLE
bug - low ram evm account creation and bridge transactions

### LINKED ISSUE #419: Native - Bridging TLOS from native to an EVM address shows weird errors that do not help user complete bridging.
On https://wallet.telos.net/native/balance
Try to send some TLOS from native to EVM address that you want:
First, it will tell you address does not exist, what causes this?
Second you hit Deposit and if you do not have enough ram you not have that communicated to you.

I propose that if the user does not have enough ram, we:
1. Inform the user that to do bridging they need to do a preparation transaction in the Telos EVM wallet that will cost 1 TLOS or however much is needed to do the transfer.
2. Queue the transaction that buys the ram needed and then the deposit transaction and have user sign both and complete their bridiging.
3. Include a link to docs that explains in detail RAM, Buying RAM and how they can get the TLOS they used to buy RAM back.

RELATED ISSUES: #314 #99 

Images related:
Error user saw:
image
Error from console:
image

### PR DESCRIPTION
**Pull request by donnyquixotic**
# Fixes #419 #314 

## Description
- See issue descriptions

## Test scenarios

1. Select 'Native' and create a new account (be sure to save keys)
2. Add Newly created account to Anchor
3. Sign in to 'Native' using Anchor and newly created account
4. click '>>> EVM' to initiate a deposit to EVM and display deposit form
5. click 'Generate New Address' 
6. see updated error instructing to view resources
7. Seed new account with 1 TLOS from external wallet (Anchor, etc)
8. return to wallet and purchase .25 TLOS worth of RAM
9. retry address generation, see success
10. Login to OBE with new account
11. Sell all available ram (after linked EVM account creation)
12. Return to web wallet
13. view resources to verify 100% ram usage
14. repeat step 4, and either send to linked address, or other address
15. see success and fuel message in Anchor transaction

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

**Review by ezra-guzman — APPROVED** [review]

File: src/pages/native/balance/DepositEVM.vue [hunk 1]
```diff
@@ -87,6 +87,12 @@ export default {
             }
         },
         async generateAddress(){
+            const accountInfo = await this.$store.$api.getAccount(this.accountName);
+
+            if (accountInfo.ram_quota - accountInfo.ram_usage <= 1000){ // If account (often newly created account) does not have sufficient RAM, notify user
```
Comment (pmjanus) [inline src/pages/native/balance/DepositEVM.vue:92]: Does the 1000 value change? can we extract it and give it a name for maintenance purposes?
