### PR TITLE
Collectible bugs bundle fix

### LINKED ISSUE #487: NFT bugs
There are a few issues as found during the demo:
1. if you select a collectible from the collectible dropdown, clicking the clear button does not seem to do anything
2. for images that don't load (broken links), use an icon to indicate this rather than allowing a broken image link (also do this for the NFT detail page). if an image takes more than 7 seconds to load, consider it broken
3. the weather station NFT from the below account has an attribute on the detail page which has no title or body; blank attrs should be filtered out
4. back button on nft detail page appears to go to the wallet page rather than nft inventory page
5. change 'rows per page' to 'collectibles per page'

Use `const owner = '0x13B745FC35b0BAC9bab9fD20B7C9f46668232607';` in `nfts.ts` to see broken image links and generally a lot of NFTs to test with

### PR DESCRIPTION
**Pull request by karynemayer**
# Fixes #487 

## Description
This PR addresses all the reproducible issues listed in #487 and a filtering issue:
1. ~clearing collectible dropdown doesn't update the list~  Could not reproduce.
2. loading for up to 5 seconds on images with broken link, then shows the broken image icon.
3. undefined attributes are filtered out
4. back button on nft detail page redirects to inventory
5. 'collectibles per page' as label
6. Search didn't work correctly when collection was not selected.

## Checklist:

-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

**Comment by Viterbo** [comment]
[viedo-loading.webm](https://github.com/telosnetwork/telos-wallet/assets/4420760/91f28efa-ce7f-4c94-a49f-26b51dd659c3)

File: src/pages/evm/nfts/NftDetailsPage.vue [hunk 1]
```diff
@@ -59,6 +59,10 @@ const ownerLink = computed(() => {
     return `${explorerUrl}/address/${nft.value.contractAddress}`;
 });
 
+const filteredAttributes = computed(() =>
+    nft.value?.attributes.filter(attr => attr.label !== undefined && attr.text !== undefined),
```
Comment (ezra-guzman) [inline src/pages/evm/nfts/NftDetailsPage.vue:63]:
```suggestion
    nft.value?.attributes.filter(attr => !!attr.label && !!attr.text),
```

suggesting because it may be that one of these is an empty string rather than undefined, in which case we still want to hide it

File: src/pages/evm/nfts/NftViewer.vue [hunk 2]
```diff
@@ -238,6 +281,20 @@ function toggleVideoPlay(playOnly?: boolean) {
         max-height: 100%;
     }
 
+    &__image-loading {
+        height: 100%;
+        width: 100%;
+    }
+
+    &__broken-image {
+    }
```
Comment (ezra-guzman) [inline src/pages/evm/nfts/NftViewer.vue:290]:
```suggestion
```

**Comment by ezra-guzman** [comment]
it looks like 2 different icons are being displayed for images which don't load:
image

using account `0x13B745FC35b0BAC9bab9fD20B7C9f46668232607` to test

**Review by donnyquixotic — APPROVED** [review]

**Review by donnyquixotic — APPROVED** [review]

**Review by ezra-guzman — CHANGES_REQUESTED** [review]
seeing another issue, with how video is displayed on the detail page:
image

i think it may have to do with the recent change where the video class was removed from an element? 
https://github.com/telosnetwork/telos-wallet/pull/509/commits/4d8a3c06c517460d364f8734a0b5d64f7aea2a08#diff-94da368bc168382af3027204253a0b6eb17ff7e14b8a7a910a38c36061374027R179

**Review by ezra-guzman — APPROVED** [review]
awesome 💯
