### PR TITLE
fallback solution works when indexer is down

### LINKED ISSUE #616: Balances never load whe indexer is down
**Describe the bug**
The fallback solution when the indexer is down is not working and balances never load.

**Expected behavior**
If the indexer is down, we need to be able to detect that situation and fall back to an alternative solution at least to load the balances of the system and ERC20 tokens.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #616

## Description
The fallback solution when the indexer is down is not working and balances never load.

This PR changes the strategy so it takes into account when the indexer is down and does not block the execution flow. Now the balances load despite the indexer not working.

## Screenshot
You can see that now is loading the balances although the indexer is still down.
Captura desde 2023-09-25 11-08-50

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage

### CODE REVIEW

File: src/api/price.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ const priceCache: { [tokenId: string]: CachedPrice } = {};
 export const getCoingeckoUsdPrice = async (
     tokenId: string,
 ): Promise<number> => {
+    console.log('getCoingeckoUsdPrice()', tokenId);
```
Comment (pmjanus) [inline src/api/price.ts:24]: We want this?

**Review by pmjanus — APPROVED** [review]
