### PR TITLE
bugfix: avoiding using scientific notation on string numbers

### LINKED ISSUE #359: SendPage gets broken when using big token balances
#Description
Tokens with very low token prices are causing the code to break when trying to create a BigNumber from a string containing scientific notation to describe a very low number.
eg:
(0.0000001234567).toString() -> '1.234567e-7'

Captura desde 2023-05-26 18-46-29

### LINKED ISSUE #386: Weird bug preventing the page to load related to BigNumber parsing
image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #359
also fixes #386

## Description
The helper function `ethers.utils.parseUnits` parses a string number to create a `BigNumber` representation but this parsing fails when the string contains a scientific notation. This PR takes care of all the cases when this helper is used making sure no string number gets represented in scientific notation.

## Test scenarios
- you need to download this branch and run it in mainnet
```bash
git fetch --all
git checkout 359-sendpage-gets-broken-when-using-big-token-balances-1
echo 'NETWORK="mainnet"' > .env
yarn; yarn dev
```
- login on EVM using an account with some DOUGE token
   - you should see no changes on balances page
- go to send Page
- open dev tools to see console errors
- select DOUGE token
  - it should not break and continue working as expected

## Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [ ] I have checked my code and corrected any misspellings
-   [ ] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/antelope/stores/utils/currency-utils.ts [hunk 1]
```diff
@@ -3,6 +3,23 @@ import { parseUnits } from 'ethers/lib/utils';
...
+ * Given a number or string, returns a string representation of the number with up to 18 decimal places
+ * @param value - number or string to convert to string
+ * @returns {string} string representation of the number
+ */
+
+export function toStringNumber(value: number | string): string {
+    if (typeof value === 'string') {
+        return value;
+    } else if (typeof value === 'number') {
+        return value.toFixed(18);
```
Comment (EJSG) [inline src/antelope/stores/utils/currency-utils.ts:16]: this will cause issues, as js numbers cannot handle 18 places of precision (max is 16). instead use this:
```ts
const num = new Decimal(value);
const result = num.toFixed(18);
```

Comment (EJSG) [reply src/antelope/stores/utils/currency-utils.ts:16]: we already have the Decimal library on the project

Comment (Viterbo) [reply src/antelope/stores/utils/currency-utils.ts:16]: PERFECT !!!! :+1:

**Review by EJSG — APPROVED** [review]

**Review by donnyquixotic — APPROVED** [review]
