### PR TITLE
cache and try-catch for coingecko API

### LINKED ISSUE #340: Intermittent failure to list TLOS balance
Sometimes the TLOS balance is not listed when loading the balances tab. there are two components to this issue:
- this issue is happening on testnet only right now
- we should handle the scenario where the indexer endpoint fails. balances should be gotten from hyperion in this case
- we should still show balance when coingecko endpoint fails (usually due to ratelimiting) or if the fiat price is not fetched from the indexer endpoint for some reason. the balance should still come from the indexer with a fallback of hyperion

Image

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #340

## Description
Coingecko API gets blocked when the applications fetches repeatedly within a short period of time and that was causing the whole application to crash. To mitigate this problem two solutions were implemented:
1 - **Try-Catch**: Sourrinding the code with try-catch clauses is always a good practice and prevents the app from crashing
2 - **Cache**: a small cache of prices fetched within the last minute is saved to avoid constantly hitting the API.

## Test scenarios
- go to [this link](https://deploy-preview-341--wallet-staging.netlify.app/)
- Login on EVM Testnet
- open developer tools (F12 on Chrome)
- open the Network panel
- you should see an initial fetch on a link like https://api.coingecko.com/api/v3/simple/price?ids=telos...
- you should not see another fetch to Coingecko's API until 1 minute has passed.

- reload the page and wait for it to load de TLOS price
  - if it does, reload the page again
  - if it doent's you will get a Coingecko API error on the console but the token balances still display as usual but with no prices.

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file
-   [x] I have created a new issue with the required translations for the currently supported languages
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/api/price.ts [hunk 1]
```diff
@@ -5,16 +5,44 @@ import {
...
+            const price = stats.data[tokenId].usd;
+            priceCache[tokenId] = { lastFetchTime: now, lastPrice: price };
+            return price;
+        } else {
+            console.error(`Error: received status code ${stats.status} from Coingecko.`);
+            return 0;
+        }
+    } catch (error) {
+        console.error('Error: fetching from Coingecko failed.', error);
+        return 0;
```
Comment (pmjanus) [inline src/api/price.ts:44]: Will this return price as 0? If apis fail we should not return price 0 but mark it as no price was obtained and show that state to user.

**Review by pmjanus — APPROVED** [review]

File: src/api/price.ts (hunk 1 above)
Comment (Viterbo) [reply src/api/price.ts:44]: What you said is exactly what happens. The price == 0 means "no price", therefore the token price is never set therefore the balance page will show the balance with an icon with a tooltip saying exactly that: "Not reliable fiat value found"

**Review by donnyquixotic — APPROVED** [review]
