### PR TITLE
#645 | IPFS NFTs

### LINKED ISSUE #645: Investigate broken IPFS NFTs
Currently, we show NFTs which have IPFS media as a broken image icon. This is for two reasons, 1. we need to replace the raw `ipfs://` protocol part of the URL with a public IPFS gateway as is [done in Teloscan ](https://github.com/telosnetwork/teloscan/blob/dev/src/lib/ContractManager.js#L69). 2, IPFS URLs do not include a filetype extension like '.webp', so our current method of extracting the media does not work (as we currently rely on file extension to determine media type); we need to add logic to determine the MIME type of IPFS media

### PR DESCRIPTION
**Pull request by ezra-sg**
# Fixes #645 

Includes work by @Viterbo from https://github.com/telosnetwork/telos-wallet/pull/667

## Description
This PR enables viewing of IPFS NFTs. It also fixes a few issues:
- video NFTs now correctly show the hover preview when in icon mode (such as list view - NFT inventory page)
- very tall video NFTs no longer break the NFT detail page layout
- NFT detail cards (on the NFT detail page, such as "Owner" and "Description") no longer grow in height when used with very tall NFTs
- you can now access the NFT detail page when not logged in (fixed by @Viterbo - underlying issue was that the contract manager relied on a Signer, but now uses a Provider as a fallback)

## Test scenarios
- go to https://deploy-preview-665--wallet-develop-mainnet.netlify.app/
- log in
- go to an ERC721 NFT detail page, such as https://deploy-preview-665--wallet-develop-mainnet.netlify.app/evm/collectible-details?contract=0xb0DdE512a8f996412312491715c5936cee35D9F4&id=1007&tab=attributes
    - the layout should look good
- go to an ERC1155 NFT detail page, such as https://deploy-preview-665--wallet-develop-mainnet.netlify.app/evm/collectible-details?contract=0xB63d03F03A7754a7E6c9A38C312fe21e0b966a8E&id=1&tab=attributes
    - the layout should look good
- go to an IPFS NFT detail page, such as https://deploy-preview-665--wallet-develop-mainnet.netlify.app/evm/collectible-details?contract=0xcfbed196e6e53e076BC06bAc40462E7A6B594187&id=1&tab=attributes
    - you should see the NFT 

Hover working for video NFTs:

https://github.com/telosnetwork/telos-wallet/assets/11837820/841282a6-da35-436e-90ac-dd399c10e7c2

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/antelope/chains/EVMChainSettings.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ export default abstract class EVMChainSettings implements ChainSettings {
 
         // Interceptor handlers -- these handlers are used to limit the number of concurrent requests
         // eslint-disable-next-line @typescript-eslint/no-explicit-any
-        const requestHandler = (value: InternalAxiosRequestConfig) => new Promise<InternalAxiosRequestConfig<any>>((resolve) => {
+        const requestHandler = (value: any) => new Promise<any>((resolve) => {
```
Comment (ezra-sg) [inline src/antelope/chains/EVMChainSettings.ts:95]: fix new error saying `InternalAxiosRequestConfig` does not exist

File: src/pages/evm/nfts/NftInventoryPage.vue [hunk 2]
```diff
@@ -447,7 +447,7 @@ onUnmounted(() => {
                                 @click="goToDetailPage(props.row)"
                                 @keydown.space.enter.prevent="goToDetailPage(props.row)"
                             >
-                                <template v-if="props.row.image">
+                                <template v-if="props.row.image || props.row.isVideo">
```
Comment (ezra-sg) [inline src/pages/evm/nfts/NftInventoryPage.vue:450]: fix the issue where the hover preview for NFT tile icons would not show for video NFTs

File: src/pages/evm/nfts/NftViewer.vue [hunk 3]
```diff
@@ -398,7 +398,12 @@ function setHoverPreviewVisibility(visible: boolean) {
         &--preview {
             max-height: 270px;
 
-            #{$this}__image {
+            #{$this}__video-container {
```
Comment (ezra-sg) [inline src/pages/evm/nfts/NftViewer.vue:401]: fix grid blowout for tall videos

File: src/antelope/stores/utils/contracts/EvmContract.ts [hunk 4]
```diff
@@ -138,8 +138,13 @@ export default class EvmContract {
             throw new AntelopeError('antelope.utils.error_contract_instance');
         }
         const signer = await this._manager?.getSigner();
+        let provider;
 
-        return new ethers.Contract(this.address, this.abi, signer);
+        if (!signer) {
+            provider = await this._manager?.getWeb3Provider();
+        }
```
Comment (ezra-sg) [inline src/antelope/stores/utils/contracts/EvmContract.ts:145]: addresses the issue where a logged-out user cannot view NFTs because there is no signer when logged out

**Review by donnyquixotic — APPROVED** [review]

**Review by Viterbo — APPROVED** [review]
Nice, clean and working! :+1: 
Just the way I like it :ok_hand:
