### PR TITLE
SafePal login button now works inside SafePal wallet

### LINKED ISSUE #512: Injected provider does not work on SafePal wallet
... to be continued

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #512

## Description
This PR fixes the detection of the provider injected into the SefaPal wallet app. Now the button to log in with SafePal directly (without using WalletConnect) is available when running our website within the Dapps section of the SafePal wallet.

## Test scenarios
- On Mobile, open your SafePal wallet and go to Dapps section
- browse this link: https://deploy-preview-534--wallet-staging.netlify.app/
  - You should see the SafePal wallet button available.
- Press SafePal that logiun button
  - You should be logged as normal
  - You should be able to sign and send any transaction (send or un/wrap)

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x]  I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage

### CODE REVIEW

File: src/pages/home/EVMLoginButtons.vue [hunk 1]
```diff
@@ -194,6 +194,10 @@ export default defineComponent({
 </template>
 
 <style lang="scss">
+.borrame {
+    color: white;
+}
+
```
Comment (ezra-guzman) [inline src/pages/home/EVMLoginButtons.vue:200]:
```suggestion
```

**Review by donnyquixotic — APPROVED** [review]

**Comment by pmjanus** [comment]
On mobile we can detect the wallet injected so we can display that wallets button. Safepal and Metamask for now.

**Review by ezra-guzman — APPROVED** [review]
