### PR TITLE
Fixing blink of balances page when updating with indexer

### LINKED ISSUE #538: Balances blinks when updated using the indexer
## Description

When using the indexer for updating the balances, it blinks (all disappear and then appear again in less than a second).

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #538

## Description
This PR fixes the weird behavior that you can see on the balance page when the indexer is healthy (like right now on Mainnet).

## Test scenarios
- you need to run this branch locally with .evm pointing to Mainnet
`git fetch --all; git checkout 538-balances-blinks-when-updated-using-the-indexer; echo 'NETWORK="mainnet"' > .env; yarn; yarn dev`
- login with the Team Account
  - you should see a lot of tokens and their prices
  - TLOS should be on top
- wait for 20 sec
  - you should see no blink nor any weird effect
- now login using a brand new Account with no balances
  - you should see at least the three system tokens with cero balances

### Team Account nalances

image

### Brand new Account balances

image

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [x] I have added appropriate test coverage

### CODE REVIEW

File: src/antelope/stores/balances.ts [hunk 1]
```diff
@@ -99,21 +99,40 @@ export const useBalancesStore = defineStore(store_name, {
                 } else {
                     const chain_settings = chain.settings as EVMChainSettings;
                     if (account?.account) {
+
+                        // first we assert that the balances array exists and is he same until the user changes
```
Comment (donnyquixotic) [inline src/antelope/stores/balances.ts:103]:
```suggestion
                        // first we assert that the balances array exists and is the same until the user changes
```

**Review by donnyquixotic — APPROVED** [review]

**Review by ezra-guzman — APPROVED** [review]
